all:
  children:
    nokia_pe:
      hosts:
        AP-7750SR7s-PE-1:
          ansible_host: 192.168.30.13
        CA-7750SR7s-PE-1:
          ansible_host: 192.168.30.15
        LG-7750SR7s-PE-1:
          ansible_host: 192.168.30.14
        TI-7750SR7s-PE-1:
          ansible_host: 192.168.30.16
        LM-7750SR7s-PE-1:
          ansible_host: 192.168.30.17
        LF-7750SR7s-PE-1:
          ansible_host: 192.168.30.26
        CP-7750SR7s-PE-1:
          ansible_host: 192.168.30.36
        LP-7750SR7s-PE-1:
          ansible_host: 192.168.30.37
        MR-7750SR7s-PE-1:
          ansible_host: 192.168.30.35
        PI-7750SR7s-PE-1:
          ansible_host: 192.168.30.32
        MA-7750SR7s-PE-1:
          ansible_host: 192.168.30.30
        FR-7750SR7s-PE-1:
          ansible_host: 192.168.30.18
        BR-7750SR7s-PE-1:
          ansible_host: 192.168.30.33
        VL-7750SR7s-PE-1:
          ansible_host: 192.168.30.22
        LA-7750SR7s-PE-1:
          ansible_host: 192.168.30.25
        BE-7750SR7s-PE-1:
          ansible_host: 192.168.30.23
        SM-7750SR7s-PE-1:
          ansible_host: 192.168.30.29
        BA-7750SR7s-PE-1:
          ansible_host: 192.168.30.20
        VZ-7750SR7s-PE-1:
          ansible_host: 192.168.30.28
        RM-7750SR7s-PE-1:
          ansible_host: 192.168.30.21
        IZ-7750SR7s-PE-1:
          ansible_host: 192.168.30.31
        TR-7750SR7s-PE-1:
          ansible_host: 192.168.30.19
        LZ-7750SR7s-PE-1:
          ansible_host: 192.168.30.24
        DV-7750SR7s-PE-1:
          ansible_host: 192.168.30.27
        LM-MQ-7750SR7s-PE-2:
          ansible_host: 192.168.30.221
